### ISSUE TITLE
大哥可以加下你的微信，請教關於點線特徵點的雙目相機問題不

### ISSUE THREAD

**Issue by chenxiaocongAI** [flshyi/PLSLAM#1]
大哥可以加下你的微信，請教關於點線特徵點的雙目相機問題不

**Comment by chenxiaocongAI** [comment]
我的微信是：18306676394

**Comment by flshyi** [comment]
> 大哥可以加下你的微信，請教關於點線特徵點的雙目相機問題不

我只是合并了下作者的代码，随手丢上来给大家使用，并没有研究过线特征。

后续发现原作者两个工程其实改一个文件夹就可以使用了，我这就算改了几个bug吧。
